--[[
	
v1.0.7
==================================================
-Fixed a bug which gun shooting automatically even "Auto" setting is disabled
==================================================
	
v1.0.6
==================================================
-Fixed a glitch which player can shooting even after died
-Added "ChargedShot" setting
-Added "Minigun" setting
-Added "Piercing" setting
-Added "FadeTime" setting
-Updated "BulletVisualizerScript". Replace an older one now!
==================================================
	
v1.0.5
==================================================
-Fixed a gun that shoot slower even you set "FireRate" to lower
-Added "ShotgunReload" setting
==================================================
	
v1.0.4
==================================================
-Fixed VisualizeBulletScript and BulletVisualizerScript. Previously, it's a bug that doesn't show bullet for other player.
-Fixed a bug which scope still in use even unequipped
==================================================
	
v1.0.3
==================================================
-Fixed a bug that you can reload a gun even unequip
-Ray start position is now at Player's Head instead Gun Muzzle
-Added "DualEnabled" setting
-Added Ammo Box for the gun
-User can no longer use Scope while reloading
==================================================
	
v1.0.2
==================================================
-Fixed Bullet Visualizer that doesn't display fake bullet to other player
-Fixed fake bullet still displayed even "VisualizerEnabled" is disabled
==================================================
	
v1.0.1
==================================================
-Fixed reload
-Ammo GUI will not show if AmmoPerClip is "math.huge"
-Added Animation setting
==================================================
	
v1.0
==================================================
-First release
==================================================
	
--]]