while true do --Loop
script.Parent.Texture = "http://www.roblox.com/asset/?id=1465231221" --Insert decal's first texture 
wait(0.005)
script.Parent.Texture = "http://www.roblox.com/asset/?id=1465232374" --second texture
wait(0.005) --wait 1 second, you can change this and make it different for every one
script.Parent.Texture = "http://www.roblox.com/asset/?id=1465231914" 
wait(0.005)
script.Parent.Texture = "http://www.roblox.com/asset/?id=1465238174" 
wait(0.005)
end