local IMConstants = {
	SLOT_NAME_PREFIX                        = "SLOT_",
	HOVER_NAME_PREFIX                       = "HOVER_PROMPT_",
	FILLED_GUI_NAME                         = "FILLED",
	DUMMY_FILLED_GUI_NAME                   = "D_FILLED",
	GRID_LAYOUT_NAME                        = "IMGridLayout",
	
	CONTAINER_ATTRIBUTE_NAME                = "IMContainer",
	SLOT_INDEX_ATTRIBUTE_NAME               = "IMSlot",
	CONTAINER_HOTBAR_NAME                   = "Hotbar",

    DEFAULT_CELL_PADDING                    = UDim2.new(0, 10, 0, 16),
    DEFAULT_CELL_SIZE                       = UDim2.new(0, 60, 0, 60),
    DEFAULT_FILL_DIRECTION                  = Enum.FillDirection.Horizontal,
    DEFAULT_FILL_DIRECTION_MAX_CELLS        = 6,
    DEFAULT_START_CORNER                    = Enum.StartCorner.TopLeft,
    DEFAULT_H_ALIGN                         = Enum.HorizontalAlignment.Left,
    DEFAULT_V_ALIGN                         = Enum.VerticalAlignment.Top,

}


return IMConstants